package com.bpeople.finpilot.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light scheme ──────────────────────────────────────────────────────────────
val md_light_primary = Color(0xFFF97316)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFFEDD5)
val md_light_onPrimaryContainer = Color(0xFF7C2800)
val md_light_secondary = Color(0xFF06C4B0)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFDFFAF7)
val md_light_onSecondaryContainer = Color(0xFF004D47)
val md_light_tertiary = Color(0xFFF97316)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFFEDD5)
val md_light_onTertiaryContainer = Color(0xFF7C2800)
val md_light_error = Color(0xFFEF4444)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFE4E4)
val md_light_onErrorContainer = Color(0xFF7F1D1D)
val md_light_background = Color(0xFFF8FAFF)
val md_light_onBackground = Color(0xFF1E1B4B)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_onSurface = Color(0xFF1E1B4B)
val md_light_surfaceVariant = Color(0xFFEEF0FF)
val md_light_onSurfaceVariant = Color(0xFF6B7280)
val md_light_outline = Color(0xFFD1D5E8)
val md_light_outlineVariant = Color(0xFFE8EAFF)
val md_light_scrim = Color(0xFF000000)
val md_light_inverseSurface = Color(0xFF2E3058)
val md_light_inverseOnSurface = Color(0xFFF0F0FF)
val md_light_inversePrimary = Color(0xFFA5B4FC)
val md_light_surfaceTint = Color(0xFFF97316)

// ── Dark scheme ───────────────────────────────────────────────────────────────
val md_dark_primary = Color(0xFFF97316)
val md_dark_onPrimary = Color(0xFF451A00)
val md_dark_primaryContainer = Color(0xFF7C2800)
val md_dark_onPrimaryContainer = Color(0xFFFFEDD5)
val md_dark_secondary = Color(0xFF5EEAD4)
val md_dark_onSecondary = Color(0xFF003A34)
val md_dark_secondaryContainer = Color(0xFF00524A)
val md_dark_onSecondaryContainer = Color(0xFFDFFAF7)
val md_dark_tertiary = Color(0xFFFBBF24)
val md_dark_onTertiary = Color(0xFF451A00)
val md_dark_tertiaryContainer = Color(0xFF7C2800)
val md_dark_onTertiaryContainer = Color(0xFFFFEDD5)
val md_dark_error = Color(0xFFFCA5A5)
val md_dark_onError = Color(0xFF7F1D1D)
val md_dark_errorContainer = Color(0xFF991B1B)
val md_dark_onErrorContainer = Color(0xFFFFE4E4)
val md_dark_background = Color(0xFF0F1117)
val md_dark_onBackground = Color(0xFFE8E8FF)
val md_dark_surface = Color(0xFF141520)
val md_dark_onSurface = Color(0xFFE8E8FF)
val md_dark_surfaceVariant = Color(0xFF2A2D4A)
val md_dark_onSurfaceVariant = Color(0xFFA0A8C0)
val md_dark_outline = Color(0xFF4A4E72)
val md_dark_outlineVariant = Color(0xFF2A2D4A)
val md_dark_scrim = Color(0xFF000000)
val md_dark_inverseSurface = Color(0xFFE8E8FF)
val md_dark_inverseOnSurface = Color(0xFF141520)
val md_dark_inversePrimary = Color(0xFFF97316)
val md_dark_surfaceTint = Color(0xFFF97316)

// ── Finance semantic colours ──────────────────────────────────────────────────
val IncomeGreen = Color(0xFF10B981)
val ExpenseRed = Color(0xFFEF4444)
val SavingsBlue = Color(0xFF5B6AF0)
val WarningAmber = Color(0xFFF59E0B)
val NeutralGrey = Color(0xFF9CA3AF)

// ── Glass / gradient UI constants ─────────────────────────────────────────────
val GradientStart = Color(0xFFEEF0FF)
val GradientEnd = Color(0xFFEAFCFA)
val BrandColor = Color(0xFFF97316)
val PrimaryIndigo = Color(0xFF5B6AF0) // Keeping for compatibility, but BrandColor is preferred
val PrimaryTeal = Color(0xFF06C4B0)
val DeepText = Color(0xFF1E1B4B)
val SubtleText = Color(0xFF6B7280)
